[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

# マルチカーソルと範囲選択
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tomasr/molokai'
#hook_add = 'colorscheme molokai'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

#スニペット
[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'w0ng/vim-hybrid.git'

# 矩形ペーストするやつ
[[plugins]]
repo = 'hekyou/vim-rectinsert'

# 選択diffやるやつ
[[plugins]]
repo = 'kamuiroeru/BlockDiff'

# 単語ごとにdiffするやつ
[[plugins]]
repo = 'rickhowe/diffchar.vim'


[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype'

# tomlのシンタックスハイライト
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# git系
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# インデント可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'qpkorr/vim-bufkill'
