[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# [[plugins]]
# repo = 'Shougo/neocomplete'
# if = 'has("lua")'
# on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'cohama/lexima.vim'
