[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
#hook_source = 'let g:deoplete#enable_at_startup = 1'
#hock_source = '''
#    let g:deoplete#sources#clang#libclang_path = '/usr/local/Cellar/llvm/6.0.0/lib/libclang.dylib'
#    let g:deoplete#sources#clang#clang_header = '/usr/include/c++'
#'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tomasr/molokai'
#hook_add = 'colorscheme molokai'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cohama/lexima.vim'
